//
// Copyright (c) 2016 Plausible Labs Cooperative, Inc.
// All rights reserved.
//

class QueryOptimizer {
    var nodes: [QueryPlanner.Node]
    
    init(nodes: [QueryPlanner.Node]) {
        self.nodes = nodes
        
        optimize()
    }
    
    func optimize() {
        for i in nodes.indices {
            // Unions with a single child (generated by Relation changes) can be eliminated and
            // the child pointed straight at the union's parents.
            if case .Union = nodes[i].op where nodes[i].childCount == 1 {
                let childIndex = nodes[i].childIndexes[0]
                nodes[childIndex].parentIndexes = nodes[i].parentIndexes
                nodes[i].parentIndexes = []
            }
        }
    }
}
